export const recipes = [
  "Adhered Iron Plate",
  "Alclad Casing",
  "Aluminum Beam",
  "Aluminum Rod",
  "Automated Miner",
  "Automated Speed Wiring",
  "Basic Iron Ingot",
  "Biocoal",
  "Bolted Frame",
  "Bolted Iron Plate",
  "Cast Screw",
  "Caterium Circuit Board",
  "Caterium Computer",
  "Caterium Wire",
  "Charcoal",
  "Cheap Silica",
  "Classic Battery",
  "Cloudy Diamonds",
  "Coated Cable",
  "Coated Iron Canister",
  "Coated Iron Plate",
  "Coke Steel Ingot",
  "Compacted Coal",
  "Compacted Steel Ingot",
  "Cooling Device",
  "Copper Alloy Ingot",
  "Copper Rotor",
  "Crystal Computer",
  "Dark Matter Crystallization",
  "Dark Matter Trap",
  "Dark-Ion Fuel",
  "Diluted Fuel",
  "Diluted Packaged Fuel",
  "Distilled Silica",
  "Electric Motor",
  "Electrode Aluminum Scrap",
  "Electrode Circuit Board",
  "Electromagnetic Connection Rod",
  "Encased Industrial Pipe",
  "Fertile Uranium",
  "Fine Black Powder",
  "Fine Concrete",
  "Flexible Framework",
  "Fused Quartz Crystal",
  "Fused Quickwire",
  "Fused Wire",
  "Heat Exchanger",
  "Heat-Fused Frame",
  "Heavy Encased Frame",
  "Heavy Flexible Frame",
  "Heavy Oil Residue",
  "Infused Uranium Cell",
  "Instant Plutonium Cell",
  "Instant Scrap",
  "Insulated Cable",
  "Insulated Crystal Oscillator",
  "Iron Alloy Ingot",
  "Iron Pipe",
  "Iron Wire",
  "Leached Caterium Ingot",
  "Leached Copper Ingot",
  "Leached Iron ingot",
  "Molded Beam",
  "Molded Steel Pipe",
  "Nitro Rocket Fuel",
  "OC Supercomputer",
  "Oil-Based Diamonds",
  "Petroleum Diamonds",
  "Pink Diamonds",
  "Plastic AI Limiter",
  "Plastic Smart Plating",
  "Plutonium Fuel Unit",
  "Polyester Fabric",
  "Polymer Resin",
  "Pure Aluminum Ingot",
  "Pure Caterium Ingot",
  "Pure Copper Ingot",
  "Pure Iron Ingot",
  "Pure Quartz Crystal",
  "Quartz Purification",
  "Quickwire Cable",
  "Quickwire Stator",
  "Radio Connection Unit",
  "Radio Control System",
  "Recycled Plastic",
  "Recycled Rubber",
  "Rigor Motor",
  "Rubber Concrete",
  "Silicon Circuit Board",
  "Silicon High-Speed Connector",
  "Sloppy Alumina",
  "Solid Steel Ingot",
  "Steamed Copper Sheet",
  "Steel Canister",
  "Steel Cast Plate",
  "Steel Rod",
  "Steel Rotor",
  "Steel Screw",
  "Steeled Frame",
  "Stitched Iron Plate",
  "Super-State Computer",
  "Tempered Caterium Ingot",
  "Tempered Copper Ingot",
  "Turbo Blend Fuel",
  "Turbo Diamonds",
  "Turbo Electric Motor",
  "Turbo Heavy Fuel",
  "Turbo Pressure Motor",
  "Uranium Fuel Unit",
  "Wet Concrete",
  "Turbofuel",
];
